/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicine.management;
import java.sql.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author RISHABH RJ
 */
public class Med_entry extends javax.swing.JFrame {

    /**
     * Creates new form Med_entry
     */
    public Med_entry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("MEDID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 115, 44, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NEW MEDICINE DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(149, 28, 330, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("MEDNAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(53, 164, 66, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("MEDSELL:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(53, 219, 60, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("MFG_DATE: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 90, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("QUANTITY:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(355, 115, 67, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("RACK:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(355, 164, 38, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("EXP_DATE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 320, 90, 30);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(172, 102, 100, 30);
        getContentPane().add(t2);
        t2.setBounds(172, 151, 100, 30);
        getContentPane().add(t3);
        t3.setBounds(170, 210, 100, 30);

        t5.setText("DD/MM/YYYY");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(170, 320, 100, 30);
        getContentPane().add(t6);
        t6.setBounds(472, 102, 90, 30);
        getContentPane().add(t7);
        t7.setBounds(472, 151, 90, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(266, 393, 98, 42);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("MFG_ID:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(355, 219, 50, 14);
        getContentPane().add(t8);
        t8.setBounds(472, 206, 90, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("MFG_NAME:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(355, 279, 72, 14);
        getContentPane().add(t9);
        t9.setBounds(472, 266, 90, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 30, 71, 25);

        t4.setText("DD/MM/YYYY");
        getContentPane().add(t4);
        t4.setBounds(170, 260, 100, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicine/management/image/1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 640, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Categories c=new Categories();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
	{

	Class.forName("com.mysql.jdbc.Driver");

	Connection cn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/medicine","root","");
//send data to table
String sql="INSERT INTO med_detail VALUES(?,?,?,?,?,?,?)";
String sql1="INSERT INTO manufacturer VALUES(?,?,?)";
PreparedStatement pst=(PreparedStatement) cn.prepareStatement(sql);
PreparedStatement pst1=(PreparedStatement)cn.prepareStatement(sql1);
       pst.setInt(1,Integer.parseInt(t1.getText()));

	pst.setString(2,t2.getText());

	pst.setFloat(3,Float.parseFloat(t3.getText()));
        pst.setString(4,t4.getText());
	pst.setString(5,t5.getText());
			
	pst.setInt(6,Integer.parseInt(t6.getText()));
        
        pst.setString(7,t7.getText());
			
        pst.executeUpdate();
        
        pst1.setInt(1,Integer.parseInt(t8.getText()));
        
        pst1.setInt(3,Integer.parseInt(t1.getText()));

        pst1.setString(2,t9.getText());
        
        pst1.executeUpdate();
//clear all input fields
				
				
                                t1.setText("");
				t2.setText("");
				t3.setText("");
                                t4.setText("");
				t5.setText("");
                                t6.setText("");
                                t7.setText("");
                                t8.setText("");
                                t9.setText("");
	}

	catch(Exception y)

			{

				JOptionPane.showMessageDialog(null,"Incomplete Information");

			}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
	{

	Class.forName("com.mysql.jdbc.Driver");

	Connection cn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/medicine","root","");
//send data to table
String sql="INSERT INTO med_detail VALUES(?,?,?,?,?,?,?)";
String sql1="INSERT INTO manufacturer VALUES(?,?,?)";
PreparedStatement pst=(PreparedStatement) cn.prepareStatement(sql);
PreparedStatement pst1=(PreparedStatement)cn.prepareStatement(sql1);
       pst.setInt(1,Integer.parseInt(t1.getText()));

	pst.setString(2,t2.getText());

	pst.setFloat(3,Float.parseFloat(t3.getText()));
        pst.setString(4,t4.getText());
	pst.setString(5,t5.getText());
			
	pst.setInt(6,Integer.parseInt(t6.getText()));
        
        pst.setString(7,t7.getText());
			
        pst.executeUpdate();
        
        pst1.setInt(1,Integer.parseInt(t8.getText()));
        
        pst1.setInt(3,Integer.parseInt(t1.getText()));

        pst1.setString(2,t9.getText());
        
        pst1.executeUpdate();
//clear all input fields
				
				
                                t1.setText("");
				t2.setText("");
				t3.setText("");
                                t4.setText("");
				t5.setText("");
                                t6.setText("");
                                t7.setText("");
                                t8.setText("");
                                t9.setText("");
	}

	catch(Exception y)

			{

				JOptionPane.showMessageDialog(null,"Incorrect Information!!!!!");

			}
        }
    }//GEN-LAST:event_t5KeyPressed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Med_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Med_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Med_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Med_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Med_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

    private int generateId(String logindata, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
